# Generated by Django 5.1.4 on 2025-01-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120, unique=True)),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=65)),
                ('profile', models.CharField(default='default.png', max_length=128)),
            ],
        ),
    ]
