# Generated by Django 5.1.4 on 2025-01-17 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_chirp_user_alter_chirp_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirp',
            name='engagement',
            field=models.IntegerField(default=1, verbose_name='Engage Count'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128)),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.chirp')),
            ],
        ),
    ]
